/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.company.prueba.view;

import com.mycompany.prueba.model.RMIInterface;
import com.mycompany.prueba.valueobject.EspecieVO;
import com.mycompany.prueba.valueobject.PersonajeVO;

import javax.swing.*;
import java.rmi.RemoteException;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Camilo
 */
public class GUICreateCharacter extends javax.swing.JFrame {

    /**
     * Creates new form GUICreateCharacter
     */
    private RMIInterface servicioInterface;
    private String id_Especie, id_Jugador;
    public GUICreateCharacter(RMIInterface serIInt,String idEsp, String idjugador) {
        initComponents();
        servicioInterface = serIInt;
        id_Especie = idEsp;
        id_Jugador = idjugador;
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnCreateChar = new javax.swing.JButton();
        txtIdChar = new javax.swing.JTextField();
        txtNameChar = new javax.swing.JTextField();
        txtStrenChar = new javax.swing.JTextField();
        txtManaChar = new javax.swing.JTextField();
        txtEnergyChar = new javax.swing.JTextField();
        jLabelIconChar = new javax.swing.JLabel();
        jLabelFondoChar = new javax.swing.JLabel();

        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        setTitle("Create Character");

        jLabel1.setFont(new java.awt.Font("Eras Medium ITC", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Create Character");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Eras Medium ITC", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ID :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        jLabel3.setFont(new java.awt.Font("Eras Medium ITC", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Name :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 115, -1, -1));

        jLabel4.setFont(new java.awt.Font("Eras Medium ITC", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Strength :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 152, -1, -1));

        jLabel5.setFont(new java.awt.Font("Eras Medium ITC", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Mana :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 189, -1, -1));

        jLabel6.setFont(new java.awt.Font("Eras Medium ITC", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Energy :");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 226, -1, -1));

        btnCreateChar.setFont(new java.awt.Font("Eras Medium ITC", 1, 14)); // NOI18N
        btnCreateChar.setText("Create");
        btnCreateChar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateCharActionPerformed(evt);
            }
        });
        getContentPane().add(btnCreateChar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 280, 80, 30));

        txtIdChar.setName("txtIdChar"); // NOI18N
        getContentPane().add(txtIdChar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 175, -1));

        txtNameChar.setName("txtNameChar"); // NOI18N
        getContentPane().add(txtNameChar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 175, -1));

        txtStrenChar.setName("txtStrenChar"); // NOI18N
        getContentPane().add(txtStrenChar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 175, -1));

        txtManaChar.setName("txtManaChar"); // NOI18N
        getContentPane().add(txtManaChar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, 175, -1));

        txtEnergyChar.setName("txtEnerChar"); // NOI18N
        getContentPane().add(txtEnergyChar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 230, 178, -1));

        jLabelIconChar.setIcon(new javax.swing.ImageIcon("src/main/java/images/characterlogo.png")); // NOI18N
        getContentPane().add(jLabelIconChar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 30, -1, -1));

        jLabelFondoChar.setIcon(new javax.swing.ImageIcon("src/main/java/images/fondodos.jpg")); // NOI18N
        getContentPane().add(jLabelFondoChar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 340));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateCharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateCharActionPerformed
        // TODO add your handling code here:
        PersonajeVO evo = null;
        String id;
        String nombre;
        double fuerza;
        double mana;
        double energia;
        double estadoRegistro;
        Date fechaModificacion= new Date();

        id = txtIdChar.getText().trim();
        nombre = txtNameChar.getText().trim();
        energia = Double.parseDouble(txtEnergyChar.getText().trim());
        mana = Double.parseDouble(txtManaChar.getText().trim());
        fuerza = Double.parseDouble(txtStrenChar.getText().trim());
        evo = new PersonajeVO(id,nombre,fuerza,mana,energia,id_Jugador,id_Especie,1,fechaModificacion);
        try
        {
            servicioInterface.addCharater(evo);
            JOptionPane.showMessageDialog(this, "Character Create");
        }catch(Exception ex)
        {
            Logger.getLogger(GUICreatePlayer.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnCreateCharActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreateChar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelFondoChar;
    private javax.swing.JLabel jLabelIconChar;
    private javax.swing.JTextField txtEnergyChar;
    private javax.swing.JTextField txtIdChar;
    private javax.swing.JTextField txtManaChar;
    private javax.swing.JTextField txtNameChar;
    private javax.swing.JTextField txtStrenChar;
    // End of variables declaration//GEN-END:variables
}
