/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.company.prueba.view;

import com.mycompany.prueba.model.RMIInterface;
import com.mycompany.prueba.valueobject.JugadorVO;

import javax.swing.*;

import static com.sun.org.apache.xalan.internal.lib.ExsltDatetime.date;
import java.rmi.RemoteException;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Camilo
 */
public class GUICreatePlayer extends javax.swing.JFrame {

    /**
     * Creates new form GUICrear
     */
    private RMIInterface servicioInterface;
    public GUICreatePlayer(RMIInterface serIInt) {
        initComponents();
        servicioInterface = serIInt;
        this.setLocationRelativeTo(null);
        
    }

    private GUICreatePlayer() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtIdPlayer = new javax.swing.JTextField();
        txtAccPlayer = new javax.swing.JTextField();
        txtPassPlayer = new javax.swing.JTextField();
        txtNickPlayer = new javax.swing.JTextField();
        txtEmailPlayer = new javax.swing.JTextField();
        btnCreatePlayer = new javax.swing.JButton();
        jLabellog = new javax.swing.JLabel();
        jLabelFondoPla = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        setTitle("Create Player");

        jLabel1.setFont(new java.awt.Font("Eras Medium ITC", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Create Player");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, -1, -1));

        jLabel2.setFont(new java.awt.Font("Eras Medium ITC", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ID :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        jLabel3.setFont(new java.awt.Font("Eras Medium ITC", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Account :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        jLabel4.setFont(new java.awt.Font("Eras Medium ITC", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Password :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        jLabel5.setFont(new java.awt.Font("Eras Medium ITC", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Nickname :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        jLabel6.setFont(new java.awt.Font("Eras Medium ITC", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Email :");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, -1));

        txtIdPlayer.setName("txtIDPlayer"); // NOI18N
        getContentPane().add(txtIdPlayer, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 174, -1));

        txtAccPlayer.setName("txtAccPlayer"); // NOI18N
        getContentPane().add(txtAccPlayer, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 174, -1));

        txtPassPlayer.setName("txtPassPlayer"); // NOI18N
        getContentPane().add(txtPassPlayer, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, 174, -1));

        txtNickPlayer.setName("txtNickPlayer"); // NOI18N
        getContentPane().add(txtNickPlayer, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 174, -1));

        txtEmailPlayer.setName("txtEmailPlayer"); // NOI18N
        getContentPane().add(txtEmailPlayer, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, 174, -1));

        btnCreatePlayer.setFont(new java.awt.Font("Eras Medium ITC", 1, 14)); // NOI18N
        btnCreatePlayer.setText("Create");
        btnCreatePlayer.setName("btnCrearPlayer"); // NOI18N
        btnCreatePlayer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreatePlayerActionPerformed(evt);
            }
        });
        getContentPane().add(btnCreatePlayer, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 280, 90, 30));

        jLabellog.setIcon(new javax.swing.ImageIcon("src/main/java/images/playerlog.png")); // NOI18N
        getContentPane().add(jLabellog, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 80, -1, -1));

        jLabelFondoPla.setIcon(new javax.swing.ImageIcon("src/main/java/images/fondodos.jpg")); // NOI18N
        getContentPane().add(jLabelFondoPla, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, 350));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreatePlayerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreatePlayerActionPerformed
               
        JugadorVO jvo = null;
        String id;
        String cuen;
        String con;
        String apo;
        String email;
        double reg = 1;
        Date da = new Date();
        
        id = txtIdPlayer.getText().trim();
        cuen = txtAccPlayer.getText().trim();
        con = txtPassPlayer.getText().trim();
        apo = txtNickPlayer.getText().trim();
        email = txtEmailPlayer.getText().trim();
        
        jvo = new JugadorVO(id, cuen, con, apo, email, reg, da);
        try
        {
            servicioInterface.addPlayer(jvo);
            JOptionPane.showMessageDialog(this, "Player Create");
        }catch(RemoteException ex)
                {
                    Logger.getLogger(GUICreatePlayer.class.getName()).log(Level.SEVERE, null, ex);
                }
        
        
    }//GEN-LAST:event_btnCreatePlayerActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreatePlayer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelFondoPla;
    private javax.swing.JLabel jLabellog;
    private javax.swing.JTextField txtAccPlayer;
    private javax.swing.JTextField txtEmailPlayer;
    private javax.swing.JTextField txtIdPlayer;
    private javax.swing.JTextField txtNickPlayer;
    private javax.swing.JTextField txtPassPlayer;
    // End of variables declaration//GEN-END:variables
}
