/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.company.prueba.view;

import com.mycompany.prueba.model.RMIInterface;

/**
 *
 * @author Camilo
 */
public class GUIPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form GUIPrincipal
     */
    private RMIInterface servicioInterface;
    public GUIPrincipal(RMIInterface serIInt) {
        initComponents();
        servicioInterface = serIInt;
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPopupMenu2 = new javax.swing.JPopupMenu();
        jSeparator1 = new javax.swing.JSeparator();
        jMenu4 = new javax.swing.JMenu();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jLabelLogoU = new javax.swing.JLabel();
        jLabelFondo = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jmcreate = new javax.swing.JMenu();
        jmCreatePlayer = new javax.swing.JMenuItem();
        jmCreateChar = new javax.swing.JMenuItem();
        jmCreateSort = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jmDeletePlayer = new javax.swing.JMenuItem();
        jmDeleteChar = new javax.swing.JMenuItem();
        jmDeleteSort = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jmUpdatePlayer = new javax.swing.JMenuItem();
        jmUpdateChar = new javax.swing.JMenuItem();
        jmUpdateSort = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        jMenu4.setText("jMenu4");

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        jMenuItem7.setText("jMenuItem7");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        setTitle("Principal");
        jLabelLogoU.setIcon(new javax.swing.ImageIcon("src/main/java/images/logoU.png")); // NOI18N
        getContentPane().add(jLabelLogoU, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 550, 210));

        jLabelFondo.setIcon(new javax.swing.ImageIcon("src/main/java/images/fondodos.jpg")); // NOI18N
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 350));

        jMenu1.setText("Archive");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Service");

        jmcreate.setText("Create");

        jmCreatePlayer.setText("Create Player");
        jmCreatePlayer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmCreatePlayerActionPerformed(evt);
            }
        });
        jmcreate.add(jmCreatePlayer);

        jmCreateChar.setText("Create Character");
        jmCreateChar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmCreateCharActionPerformed(evt);
            }
        });
        jmcreate.add(jmCreateChar);

        jmCreateSort.setText("Create Sort");
        jmCreateSort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmCreateSortActionPerformed(evt);
            }
        });
        jmcreate.add(jmCreateSort);

        jMenu2.add(jmcreate);

        jMenu6.setText("Delete");

        jmDeletePlayer.setText("Delete Player");
        jmDeletePlayer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmDeletePlayerActionPerformed(evt);
            }
        });
        jMenu6.add(jmDeletePlayer);

        jmDeleteChar.setText("Delete Character ");
        jmDeleteChar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmDeleteCharActionPerformed(evt);
            }
        });
        jMenu6.add(jmDeleteChar);

        jmDeleteSort.setText("Delete Sort");
        jmDeleteSort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmDeleteSortActionPerformed(evt);
            }
        });
        jMenu6.add(jmDeleteSort);

        jMenu2.add(jMenu6);

        jMenu7.setText("Update");

        jmUpdatePlayer.setText("Update Player");
        jmUpdatePlayer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmUpdatePlayerActionPerformed(evt);
            }
        });
        jMenu7.add(jmUpdatePlayer);

        jmUpdateChar.setText("Update Character");
        jmUpdateChar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmUpdateCharActionPerformed(evt);
            }
        });
        jMenu7.add(jmUpdateChar);

        jmUpdateSort.setText("Update Sort");
        jmUpdateSort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmUpdateSortActionPerformed(evt);
            }
        });
        jMenu7.add(jmUpdateSort);

        jMenu2.add(jMenu7);

        jMenuItem5.setText("List");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem5);

        jMenuItem6.setText("Chart");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem6);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Help");

        jMenuItem1.setText("About");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem1);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jmCreatePlayerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmCreatePlayerActionPerformed
        GUICreatePlayer gui = new GUICreatePlayer(servicioInterface);
         gui.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jmCreatePlayerActionPerformed

    private void jmUpdatePlayerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmUpdatePlayerActionPerformed
        GUIUpdatePlayer gui = new GUIUpdatePlayer(servicioInterface);
        gui.setVisible(true);
    }//GEN-LAST:event_jmUpdatePlayerActionPerformed

    private void jmCreateCharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmCreateCharActionPerformed
        GUISeleccionarJugador gui = new GUISeleccionarJugador(servicioInterface);
        gui.setVisible(true);
    }//GEN-LAST:event_jmCreateCharActionPerformed

    private void jmCreateSortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmCreateSortActionPerformed
       GUICreateSort gui = new GUICreateSort(servicioInterface);
       gui.setVisible(true);
    }//GEN-LAST:event_jmCreateSortActionPerformed

    private void jmDeletePlayerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmDeletePlayerActionPerformed
        GUIDeletePlayer gui = new GUIDeletePlayer(servicioInterface);
        gui.setVisible(true);
    }//GEN-LAST:event_jmDeletePlayerActionPerformed

    private void jmDeleteCharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmDeleteCharActionPerformed
         GUIDeleteCharacter gui = new GUIDeleteCharacter(servicioInterface);
        gui.setVisible(true);
    }//GEN-LAST:event_jmDeleteCharActionPerformed

    private void jmDeleteSortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmDeleteSortActionPerformed
        GUIDeleteSort gui = new GUIDeleteSort(servicioInterface);
        gui.setVisible(true);
    }//GEN-LAST:event_jmDeleteSortActionPerformed

    private void jmUpdateCharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmUpdateCharActionPerformed
        GUIUpdateCharacter gui = new GUIUpdateCharacter(servicioInterface);
        gui.setVisible(true);
    }//GEN-LAST:event_jmUpdateCharActionPerformed

    private void jmUpdateSortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmUpdateSortActionPerformed
        GUIUpdateSort gui = new GUIUpdateSort(servicioInterface);
        gui.setVisible(true);
    }//GEN-LAST:event_jmUpdateSortActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
          GUIListar gui = new GUIListar(servicioInterface);
        gui.setVisible(true);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        GUIGraficar gui = new GUIGraficar(servicioInterface);
        gui.setVisible(true);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JLabel jLabelLogoU;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu jPopupMenu2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JMenuItem jmCreateChar;
    private javax.swing.JMenuItem jmCreatePlayer;
    private javax.swing.JMenuItem jmCreateSort;
    private javax.swing.JMenuItem jmDeleteChar;
    private javax.swing.JMenuItem jmDeletePlayer;
    private javax.swing.JMenuItem jmDeleteSort;
    private javax.swing.JMenuItem jmUpdateChar;
    private javax.swing.JMenuItem jmUpdatePlayer;
    private javax.swing.JMenuItem jmUpdateSort;
    private javax.swing.JMenu jmcreate;
    // End of variables declaration//GEN-END:variables
}
