/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.company.prueba.view;

import com.mycompany.prueba.model.RMIInterface;
import com.mycompany.prueba.valueobject.JugadorVO;
import java.rmi.RemoteException;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;

/**
 *
 * @author Camilo
 */
public class GUIUpdatePlayer extends javax.swing.JFrame {

    /**
     * Creates new form GUICrear
     */
    private RMIInterface servicioInterface;
    public GUIUpdatePlayer(RMIInterface serIInt) {
        initComponents();
        servicioInterface = serIInt;
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtIdPlayer = new javax.swing.JTextField();
        txtAccPlayer = new javax.swing.JTextField();
        txtPassPlayer = new javax.swing.JTextField();
        txtNickPlayer = new javax.swing.JTextField();
        txtEmailPlayer = new javax.swing.JTextField();
        btnUpdatePlayer = new javax.swing.JButton();
        jLabellog = new javax.swing.JLabel();
        btnSearch = new javax.swing.JButton();
        jLabelFondoPla = new javax.swing.JLabel();

        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Eras Medium ITC", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Update Player");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Eras Medium ITC", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ID :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        jLabel3.setFont(new java.awt.Font("Eras Medium ITC", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Account :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        jLabel4.setFont(new java.awt.Font("Eras Medium ITC", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Password :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        jLabel5.setFont(new java.awt.Font("Eras Medium ITC", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Nickname :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, -1));

        jLabel6.setFont(new java.awt.Font("Eras Medium ITC", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Email :");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, -1, -1));

        txtIdPlayer.setName("txtIDPlayer"); // NOI18N
        getContentPane().add(txtIdPlayer, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 174, -1));

        txtAccPlayer.setName("txtAccPlayer"); // NOI18N
        getContentPane().add(txtAccPlayer, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 174, -1));

        txtPassPlayer.setName("txtPassPlayer"); // NOI18N
        getContentPane().add(txtPassPlayer, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, 174, -1));

        txtNickPlayer.setName("txtNickPlayer"); // NOI18N
        getContentPane().add(txtNickPlayer, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 174, -1));

        txtEmailPlayer.setName("txtEmailPlayer"); // NOI18N
        getContentPane().add(txtEmailPlayer, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, 174, -1));

        btnUpdatePlayer.setFont(new java.awt.Font("Eras Medium ITC", 1, 14)); // NOI18N
        btnUpdatePlayer.setText("Update");
        btnUpdatePlayer.setName("btnCrearPlayer"); // NOI18N
        btnUpdatePlayer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdatePlayerActionPerformed(evt);
            }
        });
        getContentPane().add(btnUpdatePlayer, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 290, 90, 40));

        jLabellog.setIcon(new javax.swing.ImageIcon("src/main/java/images/playerlog.png")); // NOI18N
        getContentPane().add(jLabellog, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 70, 210, 220));

        btnSearch.setFont(new java.awt.Font("Eras Medium ITC", 1, 14)); // NOI18N
        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        getContentPane().add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 290, 90, 40));

        jLabelFondoPla.setFont(new java.awt.Font("Eras Medium ITC", 0, 18)); // NOI18N
        jLabelFondoPla.setIcon(new javax.swing.ImageIcon("src/main/java/images/fondodos.jpg")); // NOI18N
        getContentPane().add(jLabelFondoPla, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 360));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnUpdatePlayerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdatePlayerActionPerformed
       
        JugadorVO jvo = null;
        String id;
        String cuen;
        String con;
        String apo;
        String email;
        double reg = 1;
        Date da = new Date();
        
        id = txtIdPlayer.getText().trim();
        cuen = txtAccPlayer.getText().trim();
        con = txtPassPlayer.getText().trim();
        apo = txtNickPlayer.getText().trim();
        email = txtEmailPlayer.getText().trim();
        
        jvo = new JugadorVO(id, cuen, con, apo, email, reg, da);
        try
        {
            servicioInterface.updatePlayer(jvo);
            JOptionPane.showMessageDialog(this, "Player update");
        } catch (RemoteException ex) {
            Logger.getLogger(GUIUpdatePlayer.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
    }//GEN-LAST:event_btnUpdatePlayerActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        JugadorVO jvo = null;
        String id;
        String cue;
        String con;
        String apo;
        String email;
        
        id = txtIdPlayer.getText().trim();
        try{
           jvo = servicioInterface.getPlayer(id);
            
        }
        catch(RemoteException ex){
            Logger.getLogger(GUICreatePlayer.class.getName()).log(Level.SEVERE, null, ex);
        }
        if(jvo != null)
        {
            txtAccPlayer.setText(jvo.getCuenta());
            txtPassPlayer.setText(jvo.getContraseña());
            txtNickPlayer.setText(jvo.getApodo());
            txtEmailPlayer.setText(jvo.getEmail());
            
        }
        else{
            JOptionPane.showMessageDialog(this, "Jugador no existe");
            txtAccPlayer.setText("");
            txtPassPlayer.setText("");
            txtNickPlayer.setText("");
            txtEmailPlayer.setText("");
        }
        
        
        
        
    }//GEN-LAST:event_btnSearchActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnUpdatePlayer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelFondoPla;
    private javax.swing.JLabel jLabellog;
    private javax.swing.JTextField txtAccPlayer;
    private javax.swing.JTextField txtEmailPlayer;
    private javax.swing.JTextField txtIdPlayer;
    private javax.swing.JTextField txtNickPlayer;
    private javax.swing.JTextField txtPassPlayer;
    // End of variables declaration//GEN-END:variables
}
