/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.company.prueba.view;

import com.mycompany.prueba.model.RMIInterface;
import com.mycompany.prueba.valueobject.EspecieVO;
import com.mycompany.prueba.valueobject.JugadorVO;

import javax.swing.*;
import java.rmi.RemoteException;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Camilo
 */
public class GUIUpdateSort extends javax.swing.JFrame {

    /**
     * Creates new form GUICreateSort
     */
    private RMIInterface servicioInterface;
    public GUIUpdateSort(RMIInterface serIInt) {
        initComponents();
        servicioInterface = serIInt;
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtIDSort = new javax.swing.JTextField();
        txtNameSort = new javax.swing.JTextField();
        btnUpdateSort = new javax.swing.JButton();
        btnSearchSort = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Eras Medium ITC", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Update Sort");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Eras Medium ITC", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ID");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));

        jLabel3.setFont(new java.awt.Font("Eras Medium ITC", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Name : ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        txtIDSort.setName("txtIdSort"); // NOI18N
        txtIDSort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDSortActionPerformed(evt);
            }
        });
        getContentPane().add(txtIDSort, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 227, -1));

        txtNameSort.setName("txtNameSort"); // NOI18N
        getContentPane().add(txtNameSort, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, 227, -1));

        btnUpdateSort.setFont(new java.awt.Font("Eras Medium ITC", 1, 14)); // NOI18N
        btnUpdateSort.setText("Update");
        btnUpdateSort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateSortActionPerformed(evt);
            }
        });
        getContentPane().add(btnUpdateSort, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, 100, 30));

        btnSearchSort.setFont(new java.awt.Font("Eras Medium ITC", 1, 14)); // NOI18N
        btnSearchSort.setText("Search");
        btnSearchSort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchSortActionPerformed(evt);
            }
        });
        getContentPane().add(btnSearchSort, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, 90, 30));

        jLabel5.setIcon(new javax.swing.ImageIcon("src/main/java/images/sort.png")); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 30, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon("src/main/java/images/fondodos.jpg")); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 570, 260));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtIDSortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDSortActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDSortActionPerformed

    private void btnSearchSortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchSortActionPerformed
        EspecieVO evo = null;
        String id;
        String nom;
        double reg = 1;
        Date da = new Date();


        id = txtIDSort.getText().trim();
        try{
            evo = servicioInterface.getSort(id);

        }
        catch(RemoteException ex){
            Logger.getLogger(GUICreatePlayer.class.getName()).log(Level.SEVERE, null, ex);
        }
        if(evo != null)
        {
            txtIDSort.setText(evo.getId());
            txtNameSort.setText(evo.getNombre());


        }
        else {
            JOptionPane.showMessageDialog(this, "Jugador no existe");
            txtIDSort.setText("");
            txtNameSort.setText("");

        }
    }//GEN-LAST:event_btnSearchSortActionPerformed

    private void btnUpdateSortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateSortActionPerformed
       EspecieVO evo = null;
        String id;
        String nom;
        double reg =1;
        Date da = new Date();

        id = txtIDSort.getText().trim();
        nom = txtNameSort.getText().trim();


        evo = new EspecieVO(id,nom, reg, da);
        try
        {
            servicioInterface.updateSort(evo);
            JOptionPane.showMessageDialog(this, "La especie de tu personaje se ha actualizado");
        } catch (RemoteException ex) {
            Logger.getLogger(GUIUpdatePlayer.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_btnUpdateSortActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSearchSort;
    private javax.swing.JButton btnUpdateSort;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtIDSort;
    private javax.swing.JTextField txtNameSort;
    // End of variables declaration//GEN-END:variables
}
